version: 1.0.{build}

branches:
  only:
    - master
skip_tags: true
clone_depth: 1

image: Visual Studio 2017
build: off

before_build:
  - ps: dotnet.exe --info

build_script:
  - ps: dotnet.exe restore

test_script:
  - ps: dotnet.exe test ./test/Args.Parser.Test/Args.Parser.Test.csproj
